// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjINXjg3oPwfu_QZwRp4gApVndQgUVrEY',
    appId: '1:186213441587:web:b6ec9295eda862577e8346',
    messagingSenderId: '186213441587',
    projectId: 'emdr-1713f',
    authDomain: 'emdr-1713f.firebaseapp.com',
    storageBucket: 'emdr-1713f.firebasestorage.app',
    measurementId: 'G-BGHSKCVFMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe8VYlhgRcKlxpqQzkOxzfyCBrW3M1qo4',
    appId: '1:186213441587:android:805dc43cffe4fb1b7e8346',
    messagingSenderId: '186213441587',
    projectId: 'emdr-1713f',
    storageBucket: 'emdr-1713f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFUVJiB5UFWkAHETlKtEpt9dW9R8Q05AE',
    appId: '1:186213441587:ios:6c592b3ffa428d4b7e8346',
    messagingSenderId: '186213441587',
    projectId: 'emdr-1713f',
    storageBucket: 'emdr-1713f.firebasestorage.app',
    iosBundleId: 'com.example.projectKanso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFUVJiB5UFWkAHETlKtEpt9dW9R8Q05AE',
    appId: '1:186213441587:ios:6c592b3ffa428d4b7e8346',
    messagingSenderId: '186213441587',
    projectId: 'emdr-1713f',
    storageBucket: 'emdr-1713f.firebasestorage.app',
    iosBundleId: 'com.example.projectKanso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjINXjg3oPwfu_QZwRp4gApVndQgUVrEY',
    appId: '1:186213441587:web:7b12e45e318a3f287e8346',
    messagingSenderId: '186213441587',
    projectId: 'emdr-1713f',
    authDomain: 'emdr-1713f.firebaseapp.com',
    storageBucket: 'emdr-1713f.firebasestorage.app',
    measurementId: 'G-B50W0YHHX2',
  );
}
